name: zincenv
channels:
- bioconda
- r
- rdkit
- conda-forge
- defaults
dependencies:
- python=3.5.5
- setuptools=40.2.0
- pyyaml=3.13
- h5py=2.8.0
- rdkit=2018.03.4.0
- pandas=0.23.4
- xlrd=1.1.0
- sympy=1.2